name: bookyo_flutter
description: Una applicacion Flutter para Bookyo

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^2.6.1
  amplify_auth_cognito: ^2.6.1
  amplify_authenticator: ^2.0.0
  provider: ^6.1.2
  amplify_analytics_pinpoint: ^2.6.1
  amplify_api: ^2.6.1
  amplify_datastore: ^2.6.1
  carousel_slider: ^5.0.0
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/BOOKYO_LOGO.png
    - lib/amplify_outputs.json

